# Generated by Django 5.2.9 on 2025-12-18 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='material.material')),
                ('title', models.CharField(max_length=200)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='material.media')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('material.material',),
        ),
    ]
