# Generated by Django 5.2.9 on 2025-12-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student_material',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.material'),
        ),
        migrations.AddField(
            model_name='student_material',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='materials',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', through='student.Student_Material', to='material.material'),
        ),
    ]
