# Generated by Django 5.2.9 on 2025-12-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('primary', 'Primary'), ('preparatory', 'Preparatory'), ('high', 'High')], max_length=50)),
            ],
        ),
    ]
