# Generated by Django 5.2.9 on 2025-12-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
