# Generated by Django 5.2.9 on 2025-12-18 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_remove_media_file_media_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='url',
            new_name='file',
        ),
    ]
